# Question 1

In [1]:
#importing numpy packet
import numpy as np
#creating a numpy array
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [2]:
#creating 2 lists
list1 = []
list2 = []
#accepting 5 element in each list
#for list1
for i in range(5):
    x = int(input())
    list1.append(x)
print("List 1:",list1)
#for list2
for i in range(5):
    y = int(input())
    list2.append(y)
print("List 2:",list2)
#Converting both lists into numpy array
array1 = np.array(list1)
array2 = np.array(list2)
print("List 1 convert into array :",array1)
print("List 2 convert into array :",array2)
#concatenate both the arrays
con = np.concatenate((array1,array2))
print("the concatenation of the two arrays is :",con)
#sorting the arrays
sort = np.sort(con)
print("The sorted array is:",sort)

89
15
2
56
13
List 1: [89, 15, 2, 56, 13]
85
15
25
6
54
List 2: [85, 15, 25, 6, 54]
List 1 convert into array : [89 15  2 56 13]
List 2 convert into array : [85 15 25  6 54]
the concatenation of the two arrays is : [89 15  2 56 13 85 15 25  6 54]
The sorted array is: [ 2  6 13 15 15 25 54 56 85 89]


# Question 3 

In [3]:
#Defining the array
array = np.array([[1,6,3],[4,9,8]])
print("The array is:",array)
#Finding the dimension of the array
print("The dimension of array is:",array.ndim)
#Finding the size of the array
print("The size of array is:",array.size)

The array is: [[1 6 3]
 [4 9 8]]
The dimension of array is: 2
The size of array is: 6


# Question 4

In [6]:
#Defining the array
array = np.arange(int(input()))
#Checking the shape of 1D array created
print("Shape of 1D array is:",array.shape)
#Converting 1D array into 2D array
array_row = array [np.newaxis]
print("The row of 2D array is:",array_row.shape)
array_col=array[:,np.newaxis]
print("The column of 2D array is:",array_col.shape)

7
Shape of 1D array is: (7,)
The row of 2D array is: (1, 7)
The column of 2D array is: (7, 1)


# Question 5 

In [7]:
#creating square numpy arrays
a = np.array([[2,5],[3,9]])
b = np.array([[8,3],[6,7]])
#vertical stacking 
print("Vertical Stacking :\n",np.vstack((a,b)))
#Horizontal stacking 
print("Horizontal stacking:\n",np.hstack((a,b)))

Vertical Stacking :
 [[2 5]
 [3 9]
 [8 3]
 [6 7]]
Horizontal stacking:
 [[2 5 8 3]
 [3 9 6 7]]


# Question 6

In [9]:
array = np.array([5,6,9,8,4,3,1,7,2])
unique, counts = np.unique(array, return_counts=True)
items = np.asarray((unique, counts)).T
print(items)

[[1 1]
 [2 1]
 [3 1]
 [4 1]
 [5 1]
 [6 1]
 [7 1]
 [8 1]
 [9 1]]
